name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Забрать код из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Собрать Docker-образ и запушить в реестр
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            your-dockerhub-username/your-app:latest
          secrets: |
            DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}

      # Шаг 3: Подключиться к серверу и обновить контейнер
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull your-dockerhub-username/your-app:latest
            docker stop your-app || true
            docker rm your-app || true
            docker run -d --name your-app -p 80:80 your-dockerhub-username/your-app:latest
